################################################################
#
# This is the configurable part of the Makefile.
# It must be named 'Makefile.config'.
#
#
################################################################

################
#
# For each conditional install option, either fill in "yes" or leave 
# blank to indicate no.

# Do you want to use the GL-based renderer?
export RENDER_GL = yes

# Do you want to use the OpenInventor-based renderer?
export RENDER_IV = yes


################
#
# Define the OS to compile for and the compiler to use.

OS = Linux

C++ = g++

################
#
# Define the C++ compiler flags

C++FLAGS = -g -Wall


######### FOX Configuration
FOXINC = -I/usr/include/fox-1.6/
FOXLIB = -L/usr/lib -lFOX-1.6 -ljpeg -lpng
FOXFLAGS = -DTIME_WITH_SYS_TIME=1 -DHAVE_UNISTD_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_ZLIB_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_PNG_H=1 -DHAVE_OPENGL -DHAVE_JPEG

#########  PQP Configuration
PQPINC = 
PQPLIB = -lPQP
PQPFLAGS = 

######### X11 Configuration
XINC = -I/usr/X11R6/include
XLIB = -L/usr/X11R6/lib -L/usr/lib/i386-linux-gnu -lX11 -lXmu

########   GL Configuration
GLINC = -I/usr/X11R6/include
GLLIB = -L/usr/X11R6/lib -lglut -lGLU -lGL
GLFLAGS = 

########   OpenInventor Configuration
IVINC = 
IVLIB = -L/usr/X11R6/lib -lInventor -lInventorXt -lXm -lGLU -lGL -ldl
IVFLAGS = -DPOSIX_SOURCE -D_XOPEN_SOURCE


######### Others
OTHERINC = -I../include 
OTHERLIB = -L../lib -lm 


