.TH "marray.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
marray.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector.h>\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMultiArray\fP"
.br
.RI "\fIA multidimensional array made from a 1D vector.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_MARRAY_H\fP"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_MARRAY_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.