.TH "matrix.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vector.h'\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLMatrix\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_MATRIX_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream& \fBoperator<<\fP (ostream &O, const \fBMSLMatrix\fP &M)"
.br
.ti -1c
.RI "istream& \fBoperator>>\fP (istream &I, \fBMSLMatrix\fP &M)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_MATRIX_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & O, const \fBMSLMatrix\fP & M)"
.PP
.SS "istream& operator>> (istream & I, \fBMSLMatrix\fP & M)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.