.TH "modelnew.C" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modelnew.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <msl/model3d.h>\fP
.br
\fC#include 'modelnew.h'\fP
.br

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.