.TH "model.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'matrix.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBModel\fP"
.br
.RI "\fIThe incremental simulator model.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_MODEL_H\fP"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_MODEL_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.