.TH "MSLList" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSLList \- 
.SH SYNOPSIS
.br
.PP
\fC#include <msllist.h>\fP
.PP
Inherits \fBlist< T, A >\fP.
.PP

.SS "template<class T, class A = allocator<T>>  class MSLList"

.SH "FRIENDS AND RELATED FUNCTION DOCUMENTATION"
.PP 
.SS "template<class T, class A = allocator<T>> ostream & operator<< (ostream & out, const MSLList< T > & L)\fC [friend]\fP"
.PP
.SS "template<class T, class A = allocator<T>> istream & operator>> (istream & in, MSLList< T > & L)\fC [friend]\fP"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.