.TH "MSLPlannerWindow" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSLPlannerWindow \- 
.SH SYNOPSIS
.br
.PP
\fC#include <guiplanner.h>\fP
.PP
Inherits \fBFXMainWindow\fP.
.PP
.SH "FRIENDS AND RELATED FUNCTION DOCUMENTATION"
.PP 
.SS "class GuiPlanner\fC [friend]\fP"
.PP
.SS "class MSLPlotWindow\fC [friend]\fP"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.