.TH "MSLPlotWindow" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSLPlotWindow \- 
.SH SYNOPSIS
.br
.PP
\fC#include <guiplanner.h>\fP
.PP
Inherits \fBFXDialogBox\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "long \fBonPaint\fP (FXObject *,FXSelector, void *)"
.br
.ti -1c
.RI "long \fBonCmdPrint\fP (FXObject *,FXSelector, void *)"
.br
.ti -1c
.RI "\fBMSLPlotWindow\fP (\fBMSLPlannerWindow\fP *owner)"
.br
.ti -1c
.RI "void \fBdrawPage\fP (FXDC &dc, FXint w, FXint h, FXint tx=0, FXint ty=0)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "MSLPlotWindow::MSLPlotWindow (\fBMSLPlannerWindow\fP * owner)"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "void MSLPlotWindow::drawPage (FXDC & dc, FXint w, FXint h, FXint tx = 0, FXint ty = 0)"
.PP
.SS "long MSLPlotWindow::onCmdPrint (FXObject *, FXSelector, void *)"
.PP
.SS "long MSLPlotWindow::onPaint (FXObject *, FXSelector, void * ptr)"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.