.TH "point3d.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point3d.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream.h>\fP
.br
\fC#include <list.h>\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLPoint3d\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_POINT3D_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream& \fBoperator<<\fP (ostream &O, const \fBMSLPoint3d\fP &p)"
.br
.ti -1c
.RI "istream& \fBoperator>>\fP (istream &I, \fBMSLPoint3d\fP &p)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_POINT3D_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & O, const \fBMSLPoint3d\fP & p)"
.PP
.SS "istream& operator>> (istream & I, \fBMSLPoint3d\fP & p)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.