.TH "random.C" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'random.h'\fP
.br
\fC#include <time.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRANDMAX\fP   0x7FFFFFFF"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define RANDMAX   0x7FFFFFFF"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.