.TH "renderpf.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderpf.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'triangle.h'\fP
.br
\fC#include 'render.h'\fP
.br
\fC#include <Performer/pf/pfChannel.h>\fP
.br
\fC#include <Performer/pf/pfEarthSky.h>\fP
.br
\fC#include <Performer/pf/pfLightSource.h>\fP
.br
\fC#include <Performer/pf/pfNode.h>\fP
.br
\fC#include <Performer/pf/pfGeode.h>\fP
.br
\fC#include <Performer/pf/pfText.h>\fP
.br
\fC#include <Performer/pf/pfScene.h>\fP
.br
\fC#include <Performer/pf/pfGroup.h>\fP
.br
\fC#include <Performer/pf/pfSwitch.h>\fP
.br
\fC#include <Performer/pf/pfDCS.h>\fP
.br
\fC#include <Performer/pf/pfSCS.h>\fP
.br
\fC#include <Performer/pr/pfGeoSet.h>\fP
.br
\fC#include <Performer/pr/pfGeoState.h>\fP
.br
\fC#include <Performer/pr/pfString.h>\fP
.br
\fC#include <Performer/pr/pfFont.h>\fP
.br
\fC#include <Performer/pr/pfMaterial.h>\fP
.br
\fC#include <Performer/pfui.h>\fP
.br
\fC#include <Performer/pfutil.h>\fP
.br
\fC#include <Performer/pfdu.h>\fP
.br
\fC#include <Performer/pr.h>\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRenderPerformer\fP"
.br
.RI "\fIPerform 3D rendering using the SGI IRIS Performer library.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_RENDERPF_H\fP"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_RENDERPF_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.