.TH "rrtslide.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rrtslide.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <vector.h>\fP
.br
\fC#include <msl/tree.h>\fP
.br
\fC#include <msl/rrt.h>\fP
.br
\fC#include <msl/defs.h>\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRRTSlide\fP"
.br
.RI "\fIIn the Connect method, slide along the walls.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.