.TH "scene.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'problem.h'\fP
.br
\fC#include 'util.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.RI "\fIAn interface class that gives \fBProblem\fP information to \fBRender\fP. It tells the renderer how the 'scene' appears for rendering purposes, as opposed to collision-detection purposes.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_SCENE_H\fP"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_SCENE_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.