.TH "setup.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_SETUP_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSetupProblem\fP (\fBModel\fP *&m, \fBGeom\fP *&g, string path)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_SETUP_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "void SetupProblem (\fBModel\fP *& m, \fBGeom\fP *& g, string path)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.