.TH "solver.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'problem.h'\fP
.br
\fC#include 'util.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBSolver\fP"
.br
.RI "\fIThe base class for all path planners.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_SOLVER_H\fP"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_SOLVER_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.