.TH "vector.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stream.h>\fP
.br
\fC#include <list.h>\fP
.br
\fC#include <vector.h>\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLVector\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMSL_VECTOR_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerror_handler\fP (int i, const char *s)"
.br
.ti -1c
.RI "ostream& \fBoperator<<\fP (ostream &O, const \fBMSLVector\fP &v)"
.br
.ti -1c
.RI "istream& \fBoperator>>\fP (istream &I, \fBMSLVector\fP &v)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define MSL_VECTOR_H"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "void error_handler (int i, const char * s)"
.PP
.SS "ostream& operator<< (ostream & O, const \fBMSLVector\fP & v)"
.PP
.SS "istream& operator>> (istream & I, \fBMSLVector\fP & v)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.